export const ApiEndPoint = {
  register: 'player/register',
  socialLogin: 'player/socialLogin',
  playerLogin: 'player/playerLogin',
  playerLogout: 'player/playerLogout',
  forgetPassword: 'player/forgetPassword',
  changePassword: 'player/changePassword',
  termsCondition: 'player/termsCondition',
  privacyPolicy: 'player/privacyPolicy',
  drawDetails: 'player/drawDetails',
  getSelectedNumber: 'player/getSelectedNumber',
  subscriptionPost: 'player/subscriptionPost',
  manualNumberPick: 'player/manualNumberPick',
  autoRandomPick: 'player/autoRandomPick',
  autoSpecificPick: 'player/autoSpecificPick',
  submitAutoSpecificNumber: 'player/submitAutoSpecificNumber',
  specificPickNumbersList: 'player/specificPickNumbersList',
  specificNumberEdit: 'player/specificNumberEdit',
  specificNumberDelete: 'player/specificNumberDelete',
  accountDetails: 'player/accountDetails',
  upgradeSubscription: 'player/upgradeSubscription',
  downgradeSubscription: 'player/downgradeSubscription',
  cancelSubscription1: 'player/cancelSubscription',
  updateProfile: 'player/updateProfile',
  updateAddress: 'player/updateAddress',
  withdrawRequest: 'player/withdrawRequest/create',
  getPlayerInfo: 'player/getPlayerInfo',

  getAllSubscriptionPlans: 'admin/getAllSubscriptionPlans',
  createSubscription: 'admin/subscription/create',
  cancelSubscription: 'admin/paypal/cancelSubscription',

  getProductList: 'getProductList',
  createPaymentLink: 'player/createPaymentLink',
  changeSubscription: 'player/changeSubscription',
  cancelStripeSubscription: 'player/cancelSubscription',
  deletePlayer: 'player/deletePlayer',
};
