export const ApiEndPoint = {
  register: 'register',
  socialLogin: 'socialLogin',
  playerLogin: 'playerLogin',
  playerLogout: 'playerLogout',
  forgetPassword: 'forgetPassword',
  termsCondition: 'termsCondition',
  privacyPolicy: 'privacyPolicy',
  drawDetails: 'drawDetails',
  getSelectedNumber: 'getSelectedNumber',
  subscriptionPost: 'subscriptionPost',
  manualNumberPick: 'manualNumberPick',
  autoRandomPick: 'autoRandomPick',
  autoSpecificPick: 'autoSpecificPick',
  submitAutoSpecificNumber: 'submitAutoSpecificNumber',
  specificPickNumbersList: 'specificPickNumbersList',
  specificNumberEdit: 'specificNumberEdit',
  specificNumberDelete: 'specificNumberDelete',
  accountDetails: 'accountDetails',
  upgradeSubscription: 'upgradeSubscription',
  downgradeSubscription: 'downgradeSubscription',
};
