export const RESET_DATA = 'RESET_REWARD_DATA_NEW_DATA';
export const FETCHING_DATA = 'FETCHING_REWARD_DATA_NEW_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_REWARD_DATA_NEW_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_REWARD_DATA_NEW_DATA_FAILURE';
